### ISSUE TITLE
Prettier error when [re]generating entity

### ISSUE THREAD

**Issue by smunir** [elhoutico/jhipster-primeng-blueprint#16]
Hi I am new to Jhipster Angular and PrimeNG Blueprint. After creating application, I am getting error on [re]generating entity. I am getting this error only when using this primeng-blueprint. I tried it with Jhipster v6.8.0 and 6.9.1:

**yo-rc.json**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.vibgo.edu.vesi"
    },
    "jhipsterVersion": "6.9.1",
    "applicationType": "monolith",
    "baseName": "vesi",
    "packageName": "com.vibgo.edu.vesi",
    "packageFolder": "com/vibgo/edu/vesi",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YmVmY2YzYzNmOWEwNjhhZGFhZGY4MzhhYmEyOGNiMWUyMDUxYWMxNjEzZjFjNDNhMDQ0ZjJhMWM3NTc3ZDQ1ZWI3OWU0YWZiYTVmNmQyMTc5YzM0NmI5NWZkYjU5ZjBlOTJjNzRjMTVlMzk1YmJmMTI0NzMwY2QwYjk1NmFlNGE=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1593089269527,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-primeng-blueprint",
        "version": "6.8.0"
      }
    ],
    "enableTranslation": false,
    "blueprints": [
      {
        "name": "generator-jhipster-primeng-blueprint",
        "version": "6.8.0"
      }
    ]
  }
}

```

**Exception:** 
 
```
Everything is configured, generating the entity...

     info Using blueprint generator-jhipster-primeng-blueprint for entity-client subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-i18n subgenerator
   create .jhipster/SystemParameter.json
   create src/main/resources/config/liquibase/changelog/20200625125629_added_entity_SystemParameter.xml
   create src/main/resources/config/liquibase/fake-data/system_parameter.csv
   create src/main/java/com/vibgo/edu/vesi/domain/SystemParameter.java
   create src/main/java/com/vibgo/edu/vesi/repository/SystemParameterRepository.java
   create src/main/java/com/vibgo/edu/vesi/web/rest/SystemParameterResource.java
   create src/main/java/com/vibgo/edu/vesi/repository/search/SystemParameterSearchRepository.java
   create src/test/java/com/vibgo/edu/vesi/web/rest/SystemParameterResourceIT.java
   create src/test/java/com/vibgo/edu/vesi/repository/search/SystemParameterSearchRepositoryMockConfiguration.java
   create src/test/java/com/vibgo/edu/vesi/domain/SystemParameterTest.java
 conflict src/main/resources/config/liquibase/master.xml
? Overwrite src/main/resources/config/liquibase/master.xml? overwrite this and all others
    force src/main/resources/config/liquibase/master.xml
    force src/main/java/com/vibgo/edu/vesi/config/CacheConfiguration.java
   create src/main/webapp/app/entities/system-parameter/system-parameter.component.html
   create src/main/webapp/app/entities/system-parameter/system-parameter-detail.component.html
   create src/main/webapp/app/entities/system-parameter/system-parameter-update.component.html
    force src/main/webapp/app/layouts/navbar/navbar.component.html
   create src/main/webapp/app/shared/model/system-parameter.model.ts
   create src/main/webapp/app/entities/system-parameter/system-parameter.module.ts
   create src/main/webapp/app/entities/system-parameter/system-parameter.route.ts
SyntaxError: ';' expected. (59:103)
  57 |             switchMap(() => {
  58 |                 if (this.currentSearch) {
> 59 |                     this.systemParameterService.search(this.systemParameterTable.filters.global.value)),
     |                                                                                                       ^
  60 |                 } else {
  61 |                     return this.systemParameterService.query(lazyLoadEventToServerQueryParams(this.systemParameterTable.createLazyLoadMetadata())));
  62 |                 }
    at t (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/parser-typescript.js:1:285)
    at Object.parse (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:13252:23)
    at format (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:13526:12)
    at /Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:44226:12)
    at /Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/generator-jhipster/generators/generator-transforms.js:44:39
```

**Comment by yelhouti** [comment]
@smunir thank you for reporting I will try to fix it ASAP, could send me the JDL part that causes problem.

**Comment by smunir** [comment]
@yelhouti I didn't use any JDL yet as I am trying to grasp concept and usage of PrimeNG Blueprint, we need to use for our project. I created this entity from CLI with three test fields (code, name, addedAt). I just tried it with generator-jhipster-primeng-blueprint 'latest' version and getting same error. Please let me know if any other info is needed

**Comment by yelhouti** [comment]
@smunir yeah, don't do that, always use JDL, here is how we do it:
https://gist.github.com/yelhouti/bcefa769a421dd60298b34ad653a4d86
Let me know if you need any help, closing this for now, unless you are able to reproduce it with JDL

**Comment by smunir** [comment]
Still facing same issue. I generated code using JDL given below: 

```
CODE_MIN_LEN = 1
CODE_MAX_LEN = 30
NAME_MIN_LEN = 1
NAME_MAX_LEN = 100
DESC_MIN_LEN = 0
DESC_MAX_LEN = 255
PHONE_MAX_LEN = 30
MOBILE_MAX_LEN = 30
EMAIL_MAX_LEN = 50
NOTIF_MAX_LEN = 400
RFID_MAX_LEN = 100
ADDRESS_LINE_MAX_LEN = 150
NOTIF_TITLE_MAX_LEN = 40
ATTACHMENT_MAX_SIZE = 10

entity InstituteParameters {
	name String required minlength(NAME_MIN_LEN) maxlength(NAME_MAX_LEN)

	logo ImageBlob
	logoSize Integer
	logoFilename String
	
	banner ImageBlob
	bannerSize Integer
	bannerFilename String

	currency String maxlength(10)
	// departmentHeirarchy Boolean //TBD
	
	email String maxlength(100)
	website String maxlength(100)
}

entity Branch {
	code String required minlength(CODE_MIN_LEN) maxlength(CODE_MAX_LEN)
	name String required minlength(NAME_MIN_LEN) maxlength(NAME_MAX_LEN)

	logo ImageBlob
	logoSize Integer
	logoFilename String

	banner ImageBlob
	bannerSize Integer
	bannerFilename String

	phone String maxlength(30)
	mobile String maxlength(30)
	email String maxlength(100)
	notifyEmailIds String maxlength(255)

	headBranch Boolean
	active Boolean

	version Integer
}

entity Campus {
	code String required minlength(CODE_MIN_LEN) maxlength(CODE_MAX_LEN)
	name String required minlength(NAME_MIN_LEN) maxlength(NAME_MAX_LEN)

	logo ImageBlob
	logoSize Integer
	logoFilename String

	banner ImageBlob
	bannerSize Integer
	bannerFilename String

	phone String maxlength(30)
	mobile String maxlength(30)
	email String maxlength(100)
	notifyEmailIds String maxlength(255)

	active Boolean

	version Integer
} // branch





relationship ManyToOne {
	Campus { branch (name) required } to Branch
	
	

}

//relationship ManyToMany {
//	Subject { branchClass } to BranchClass{ subject }
////	Student{classSection} to ClassSection{student}
//}

paginate * with pagination
dto * with mapstruct
service * with serviceClass
search * with elasticsearch
filter *
```

**yo-rc.json**
```
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "vesi",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "clientPackageManager": "npm",
    "packageName": "com.vibgo.edu.vesi",
    "packageFolder": "com/vibgo/edu/vesi",
    "blueprints": [
      {
        "name": "generator-jhipster-primeng-blueprint",
        "version": "6.8.0"
      }
    ],
    "useSass": true,
    "dtoSuffix": "DTO",
    "jhipsterVersion": "6.9.1",
    "creationTimestamp": 1593128520346,
    "skipServer": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jwtSecretKey": "YTFlNTQ4OGI2Yjc4NDg1MDk0OWY4YzZkN2EzMmFiMmViZjUwZDhmN2M0MmVhNDU0N2ViMGEyZDE0Yjg4MTJlMjlhMzI4NDdlNzg1NTk2ZjZkODc0NmFhNjc1MThjYzUwNWZmMDg5YWQwZjUzOGNlNWZlN2IyMGRjYWQ0MDM4OTE=",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "otherModules": [
      {
        "name": "generator-jhipster-primeng-blueprint",
        "version": "6.8.0"
      }
    ]
  },
  "entities": ["InstituteParameters", "Branch", "Campus"]
}
```

**Error:**
```
Found the .jhipster/InstituteParameters.json configuration file, entity can be automatically generated!


The entity InstituteParameters is being updated.


Found the .jhipster/Branch.json configuration file, entity can be automatically generated!


The entity Branch is being updated.


Found the .jhipster/Campus.json configuration file, entity can be automatically generated!


The entity Campus is being updated.

     info Using blueprint generator-jhipster-primeng-blueprint for entity-client subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-i18n subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-client subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-i18n subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-client subgenerator
     info Using blueprint generator-jhipster-primeng-blueprint for entity-i18n subgenerator
   create src/main/resources/config/liquibase/changelog/20200625234303_added_entity_InstituteParameters.xml
   create src/main/resources/config/liquibase/fake-data/institute_parameters.csv
   create src/main/resources/config/liquibase/fake-data/blob/hipster.png
   create src/main/java/com/vibgo/edu/vesi/domain/InstituteParameters.java
   create src/main/java/com/vibgo/edu/vesi/repository/InstituteParametersRepository.java
   create src/main/java/com/vibgo/edu/vesi/web/rest/InstituteParametersResource.java
   create src/main/java/com/vibgo/edu/vesi/service/dto/InstituteParametersCriteria.java
   create src/main/java/com/vibgo/edu/vesi/service/InstituteParametersQueryService.java
   create src/main/java/com/vibgo/edu/vesi/repository/search/InstituteParametersSearchRepository.java
   create src/main/java/com/vibgo/edu/vesi/service/InstituteParametersService.java
   create src/main/java/com/vibgo/edu/vesi/service/dto/InstituteParametersDTO.java
   create src/main/java/com/vibgo/edu/vesi/service/mapper/EntityMapper.java
   create src/main/java/com/vibgo/edu/vesi/service/mapper/InstituteParametersMapper.java
   create src/test/java/com/vibgo/edu/vesi/web/rest/InstituteParametersResourceIT.java
   create src/test/java/com/vibgo/edu/vesi/repository/search/InstituteParametersSearchRepositoryMockConfiguration.java
   create src/test/java/com/vibgo/edu/vesi/domain/InstituteParametersTest.java
   create src/test/java/com/vibgo/edu/vesi/service/dto/InstituteParametersDTOTest.java
   create src/test/java/com/vibgo/edu/vesi/service/mapper/InstituteParametersMapperTest.java
    force src/main/resources/config/liquibase/master.xml
    force src/main/java/com/vibgo/edu/vesi/config/CacheConfiguration.java
   create src/main/webapp/app/entities/institute-parameters/institute-parameters.component.html
   create src/main/webapp/app/entities/institute-parameters/institute-parameters-detail.component.html
   create src/main/webapp/app/entities/institute-parameters/institute-parameters-update.component.html
    force src/main/webapp/app/layouts/navbar/navbar.component.html
   create src/main/resources/config/liquibase/changelog/20200625234403_added_entity_Branch.xml
   create src/main/resources/config/liquibase/fake-data/branch.csv
   create src/main/java/com/vibgo/edu/vesi/domain/Branch.java
   create src/main/java/com/vibgo/edu/vesi/repository/BranchRepository.java
   create src/main/java/com/vibgo/edu/vesi/web/rest/BranchResource.java
   create src/main/java/com/vibgo/edu/vesi/service/dto/BranchCriteria.java
   create src/main/java/com/vibgo/edu/vesi/service/BranchQueryService.java
   create src/main/java/com/vibgo/edu/vesi/repository/search/BranchSearchRepository.java
   create src/main/java/com/vibgo/edu/vesi/service/BranchService.java
   create src/main/java/com/vibgo/edu/vesi/service/dto/BranchDTO.java
   create src/main/java/com/vibgo/edu/vesi/service/mapper/BranchMapper.java
   create src/test/java/com/vibgo/edu/vesi/web/rest/BranchResourceIT.java
   create src/test/java/com/vibgo/edu/vesi/repository/search/BranchSearchRepositoryMockConfiguration.java
   create src/test/java/com/vibgo/edu/vesi/domain/BranchTest.java
   create src/test/java/com/vibgo/edu/vesi/service/dto/BranchDTOTest.java
   create src/test/java/com/vibgo/edu/vesi/service/mapper/BranchMapperTest.java
   create src/main/webapp/app/entities/branch/branch.component.html
   create src/main/webapp/app/entities/branch/branch-detail.component.html
   create src/main/webapp/app/entities/branch/branch-update.component.html
   create src/main/resources/config/liquibase/changelog/20200625234503_added_entity_Campus.xml
   create src/main/resources/config/liquibase/changelog/20200625234503_added_entity_constraints_Campus.xml
   create src/main/resources/config/liquibase/fake-data/campus.csv
   create src/main/java/com/vibgo/edu/vesi/domain/Campus.java
   create src/main/java/com/vibgo/edu/vesi/repository/CampusRepository.java
   create src/main/java/com/vibgo/edu/vesi/web/rest/CampusResource.java
   create src/main/java/com/vibgo/edu/vesi/service/dto/CampusCriteria.java
   create src/main/java/com/vibgo/edu/vesi/service/CampusQueryService.java
   create src/main/java/com/vibgo/edu/vesi/repository/search/CampusSearchRepository.java
   create src/main/java/com/vibgo/edu/vesi/service/CampusService.java
   create src/main/java/com/vibgo/edu/vesi/service/dto/CampusDTO.java
   create src/main/java/com/vibgo/edu/vesi/service/mapper/CampusMapper.java
   create src/test/java/com/vibgo/edu/vesi/web/rest/CampusResourceIT.java
   create src/test/java/com/vibgo/edu/vesi/repository/search/CampusSearchRepositoryMockConfiguration.java
   create src/test/java/com/vibgo/edu/vesi/domain/CampusTest.java
   create src/test/java/com/vibgo/edu/vesi/service/dto/CampusDTOTest.java
   create src/test/java/com/vibgo/edu/vesi/service/mapper/CampusMapperTest.java
   create src/main/java/com/vibgo/edu/vesi/domain/enumeration/EnrollmentType.java
   create src/main/webapp/app/entities/campus/campus.component.html
   create src/main/webapp/app/entities/campus/campus-detail.component.html
   create src/main/webapp/app/shared/model/institute-parameters.model.ts
   create src/main/webapp/app/entities/institute-parameters/institute-parameters.module.ts
   create src/main/webapp/app/entities/institute-parameters/institute-parameters.route.ts
SyntaxError: ';' expected. (60:111)
  58 |             switchMap(() => {
  59 |                 if (this.currentSearch) {
> 60 |                     this.instituteParametersService.search(this.instituteParametersTable.filters.global.value)),
     |                                                                                                               ^
  61 |                 } else {
  62 |                     return this.instituteParametersService.query(lazyLoadEventToServerQueryParams(this.instituteParametersTable.createLazyLoadMetadata())));
  63 |                 }
    at t (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/parser-typescript.js:1:285)
    at Object.parse (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:13252:23)
    at format (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:13526:12)
    at /Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/prettier/index.js:44226:12)
    at /Users/shahzad/Shahzad/Personal/Projects/vims/isl/code/vesi/node_modules/generator-jhipster/generators/generator-transforms.js:44:39
```

**Comment by smunir** [comment]
Please also update latest code in NPM, was getting _Fix issues #8 Enum with no validation rule error_ therefore had to install from git

**Comment by smunir** [comment]
I also tried this with application config in JDL but got same error:

```
application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName vesi
    buildTool maven
    cacheProvider ehcache
    clientFramework angularX
    clientPackageManager npm
    databaseType sql
    prodDatabaseType mysql
    devDatabaseType mysql
    enableSwaggerCodegen false
    enableTranslation true
    languages [en]
    nativeLanguage en
    packageName com.vibgo.edu.vesi
    testFrameworks [protractor]
    blueprints [generator-jhipster-primeng-blueprint]
    useSass true
    enableHibernateCache true
    jhiPrefix jhi
    dtoSuffix DTO
    searchEngine elasticsearch
    serverPort 8080
    skipClient false
  }

entities *
}
```
